### ISSUE TITLE
Improve UI Design for Better Aesthetics for Login Page

### ISSUE THREAD

**Issue by YashChaudhary16** [YHY-NCSU/wolfjobs_fall_24#1]
The current UI is too simple, featuring a plain white background and minimal styling and the elements are not properly placed in the login page. It lacks visual appeal and fails to engage users as the main login block is not in the center. We need to enhance the design by adding background elements and a more appealing color scheme on this page.

**Comment by Yuvraj-SB** [comment]
Improved
