### ISSUE TITLE
Add Hover Effects and Color Code

### ISSUE THREAD

**Issue by YashChaudhary16** [YHY-NCSU/wolfjobs_fall_24#11]
The website currently lacks hover effects across various elements, resulting in a dull user experience. Additionally, a specific color code is missing, which affects the overall design consistency. This issue aims to implement hover effects for interactive elements and incorporate the specified color code to enhance the visual appeal and usability of the site. @harshchaudhari08

**Comment by harshchaudhari08** [comment]
Hover effects and colors have been added.
